version: "3"
services:
  app:
    container_name: ExpenseTracker
    restart: always
    build: .
    ports:
      - 80:3000
    links: mongo
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
# networks:
#   default:
#     external: true
#     name: docker-container-network
